version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        patterns:
          - "ruff"
          - "mypy"
          - "pytest*"
          - "pre-commit"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
